[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "databricks_ecommerce_lakehouse"
version = "0.1.0"
description = "E-commerce Lakehouse pipeline on Databricks"
authors = [
    { name = "Developer" }
]
dependencies = [
    "databricks-sdk>=0.30.0",
    "kaggle"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 100
